# Generated by Django 2.0 on 2021-04-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200, verbose_name='Product name')),
                ('product_price', models.FloatField()),
                ('product_description', models.TextField(verbose_name='description')),
                ('product_count', models.IntegerField()),
                ('product_is_active', models.BooleanField()),
            ],
        ),
    ]
